"use strict";
window.HOMEBOUND_VERSION="4.1.0";

(()=>{
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const MAIN_KEY="freedomCountdownData", FAMILY_KEY="freedomCountdownFamilyData", HB_KEY="homeboundV41Data", SNAPSHOT_KEY="homeboundV41Recovery", BACKUP_TIME_KEY="homeboundLastExport";
const ORIGINAL={cc1:9209.08,cc2:18803,zipPlus:3846,zipMoney:2509,car:35221};
const placeMap=[
 {id:"car",name:"Scenic Lookout",icon:"🌄",art:"🔭",description:"The first viewpoint on your road home. This place represents your vehicle finance."},
 {id:"zipMoney",name:"Forest Bend",icon:"🌲",art:"🌳",description:"A gentle bend in the road representing one of your shorter commitments."},
 {id:"zipPlus",name:"River Crossing",icon:"🌉",art:"🏞️",description:"A bridge between where you began and where you are heading."},
 {id:"cc1",name:"Mountain Pass",icon:"⛰️",art:"🏔️",description:"A steady climb that rewards consistency and patience."},
 {id:"cc2",name:"Sunrise Point",icon:"🌅",art:"☀️",description:"The last major financial climb before the road opens towards home."},
 {id:"home",name:"Home",icon:"🏡",art:"🏠",description:"The destination: consumer freedom, strong savings and a life built together."}
];
const accountLabels={car:"Car loan",zipMoney:"Zip Money",zipPlus:"Zip Plus",cc1:"Credit Card 1",cc2:"Credit Card 2"};
const gardenZones=[
 {id:"savings",name:"Savings Grove",icon:"🌳",level:1,description:"Represents money set aside for your future. Every contribution helps the grove grow stronger."},
 {id:"safety",name:"Safety Greenhouse",icon:"🌿",level:2,description:"Represents your emergency fund—the protected space that keeps your plans safe during unexpected seasons."},
 {id:"prosperity",name:"Prosperity Garden",icon:"🌻",level:2,description:"Represents your net worth and the progress created by reducing commitments while growing assets."},
 {id:"dreams",name:"Dream Meadow",icon:"🌸",level:1,description:"Every flower represents a shared dream. Add plans, targets and reminders to help each one bloom."},
 {id:"orchard",name:"Orchard",icon:"🍎",level:3,description:"Represents investments and long-term assets that may bear fruit over time."},
 {id:"homePath",name:"Home Path",icon:"🏡",level:2,description:"Represents your dream-home deposit and the practical steps that lead towards home ownership."},
 {id:"freedom",name:"Freedom Hill",icon:"🌄",level:5,description:"The final sanctuary, unlocked when your major commitments are cleared and your financial foundation is strong."}
];
const defaultDreams=[
 {id:uid(),name:"Dream Home",icon:"🏡",target:60000,saved:0,monthly:1500,date:"",notes:"A place that is truly ours.",colour:"purple"},
 {id:uid(),name:"Next Trip",icon:"✈️",target:5000,saved:0,monthly:275,date:"",notes:"Explore, experience and create memories.",colour:"orange"},
 {id:uid(),name:"Mini Cooper",icon:"🚗",target:20000,saved:0,monthly:700,date:"",notes:"The wife's dream car.",colour:"blue"},
 {id:uid(),name:"Anniversary Trip",icon:"❤️",target:4500,saved:0,monthly:200,date:"",notes:"Celebrating us, together.",colour:"pink"},
 {id:uid(),name:"Future Family",icon:"🧸",target:10000,saved:0,monthly:300,date:"",notes:"A dream close to our hearts.",colour:"rose"}
];
const defaults={
 version:1,finance:{fund:0,cc1:ORIGINAL.cc1,cc2:ORIGINAL.cc2,zipPlus:ORIGINAL.zipPlus,zipMoney:ORIGINAL.zipMoney,car:27617.56,history:[]},
 profile:{togetherSince:"",names:"Our family"},dreams:defaultDreams,trips:[],memories:[],wins:[],reminders:[],settings:{lastTab:"home",sounds:false},createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()
};
let state=loadState(), currentMemoryYear="all", currentWinCategory="all", pendingForm=null;

const MEDIA_DB="homeboundMediaV1", MEDIA_STORE="photos";
function openMediaDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(MEDIA_DB,1);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(MEDIA_STORE))req.result.createObjectStore(MEDIA_STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function mediaPut(id,value){const db=await openMediaDB();return new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite');tx.objectStore(MEDIA_STORE).put(value,id);tx.oncomplete=()=>{db.close();resolve(id)};tx.onerror=()=>reject(tx.error)})}
async function mediaGet(id){if(!id)return null;const db=await openMediaDB();return new Promise((resolve,reject)=>{const req=db.transaction(MEDIA_STORE).objectStore(MEDIA_STORE).get(id);req.onsuccess=()=>{db.close();resolve(req.result||null)};req.onerror=()=>reject(req.error)})}
async function mediaAll(){const db=await openMediaDB();return new Promise((resolve,reject)=>{const store=db.transaction(MEDIA_STORE).objectStore(MEDIA_STORE),keys=store.getAllKeys(),vals=store.getAll();let k,v;const done=()=>{if(k&&v){db.close();resolve(k.map((id,i)=>({id,value:v[i]})))}};keys.onsuccess=()=>{k=keys.result;done()};vals.onsuccess=()=>{v=vals.result;done()};keys.onerror=vals.onerror=()=>reject(keys.error||vals.error)})}
async function mediaReplace(items){const db=await openMediaDB();return new Promise((resolve,reject)=>{const tx=db.transaction(MEDIA_STORE,'readwrite'),store=tx.objectStore(MEDIA_STORE);store.clear();(items||[]).forEach(x=>store.put(x.value,x.id));tx.oncomplete=()=>{db.close();resolve()};tx.onerror=()=>reject(tx.error)})}
async function hydratePhotos(root=document){for(const img of root.querySelectorAll('img[data-photo-id]')){if(img.dataset.loaded)return;try{const src=await mediaGet(img.dataset.photoId);if(src){img.src=src;img.dataset.loaded='1'}}catch{}}}

function uid(){return Math.random().toString(36).slice(2)+Date.now().toString(36)}
function clone(v){return JSON.parse(JSON.stringify(v))}
function money(v){return new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD",maximumFractionDigits:0}).format(Number(v)||0)}
function dateText(v){if(!v)return "No date set"; return new Date(v+(/T/.test(v)?"":"T00:00:00")).toLocaleDateString("en-AU",{day:"numeric",month:"short",year:"numeric"})}
function safeParse(v,fallback){try{return JSON.parse(v)}catch{return fallback}}
function deepMerge(base,extra){const out=clone(base);Object.keys(extra||{}).forEach(k=>{if(extra[k]&&typeof extra[k]==="object"&&!Array.isArray(extra[k])&&out[k]&&typeof out[k]==="object"&&!Array.isArray(out[k]))out[k]=deepMerge(out[k],extra[k]);else out[k]=extra[k]});return out}
function loadState(){
 const saved=safeParse(localStorage.getItem(HB_KEY),null);
 if(saved)return deepMerge(defaults,saved);
 const legacy=safeParse(localStorage.getItem(MAIN_KEY),{}), family=safeParse(localStorage.getItem(FAMILY_KEY),{});
 const migrated=clone(defaults); migrated.finance=deepMerge(migrated.finance,legacy);
 if(Array.isArray(family.transactions)) migrated.finance.history=family.transactions;
 if(family.anniversaryDate)migrated.profile.togetherSince=family.anniversaryDate;
 migrated.dreams=migrated.dreams.map(d=>d.name==="Next Trip"?{...d,saved:Number(migrated.finance.fund||0)}:d);
 saveRaw(migrated,false); return migrated;
}
function saveRaw(next,snapshot=true){
 if(snapshot){const old=localStorage.getItem(HB_KEY);if(old)localStorage.setItem(SNAPSHOT_KEY,old)}
 next.updatedAt=new Date().toISOString(); localStorage.setItem(HB_KEY,JSON.stringify(next));
 localStorage.setItem(MAIN_KEY,JSON.stringify(next.finance));
}
function save(){saveRaw(state,true);renderAll()}
function totalDebt(){return ["cc1","cc2","zipPlus","zipMoney","car"].reduce((s,k)=>s+Number(state.finance[k]||0),0)}
function originalDebt(){return Object.values(ORIGINAL).reduce((a,b)=>a+b,0)}
function paidTotal(){return Math.max(0,originalDebt()-totalDebt())}
function debtPct(){return Math.min(100,paidTotal()/originalDebt()*100)}
function netWorth(){const dreamSaved=state.dreams.reduce((s,d)=>s+Number(d.saved||0),0);return Number(state.finance.fund||0)+dreamSaved-totalDebt()}
function daysTogether(){if(!state.profile.togetherSince)return null;return Math.max(0,Math.floor((Date.now()-new Date(state.profile.togetherSince+"T00:00:00"))/86400000))}
function gardenLevel(){const pct=debtPct(), nw=netWorth();if(totalDebt()<=0&&state.finance.fund>=5000)return 5;if(nw>=0||pct>=70)return 4;if(pct>=40||state.finance.fund>=5000)return 3;if(pct>=15||state.finance.fund>=1000)return 2;return 1}
function pct(saved,target){return target>0?Math.min(100,Math.max(0,Number(saved||0)/Number(target)*100)):0}
function toast(msg){const n=$("#toast");n.textContent=msg;n.classList.add("show");clearTimeout(n._t);n._t=setTimeout(()=>n.classList.remove("show"),2500)}
function celebrate(){if(matchMedia("(prefers-reduced-motion: reduce)").matches)return;const layer=$("#celebrationLayer");layer.innerHTML="";for(let i=0;i<36;i++){const s=document.createElement("span");s.className="confetti";s.textContent=["🎉","⭐","💚","🌸"][i%4];s.style.left=Math.random()*100+"%";s.style.setProperty("--duration",2+Math.random()*2+"s");s.style.setProperty("--drift",-90+Math.random()*180+"px");layer.appendChild(s)}setTimeout(()=>layer.innerHTML="",4500)}
function snapshotAvailable(){return !!localStorage.getItem(SNAPSHOT_KEY)}

function setTab(tab){$$('.tab-panel').forEach(p=>{const on=p.dataset.tab===tab;p.hidden=!on;p.classList.toggle('active',on)});$$('[data-tab-target]').forEach(b=>b.classList.toggle('active',b.dataset.tabTarget===tab));state.settings.lastTab=tab;saveRaw(state,false);window.scrollTo({top:0,behavior:'smooth'})}

function renderAll(){renderHeader();renderHome();renderJourney();renderGarden();renderDreams();renderAdventures();renderMemories();renderWins();renderNotifications();$("#recoveryBanner").hidden=!snapshotAvailable()}
function renderHeader(){const hour=new Date().getHours();$("#greeting").innerHTML=`Good ${hour<12?'morning':hour<18?'afternoon':'evening'},<br>welcome home 👋`;const notifications=getNotifications();$("#notificationBadge").hidden=!notifications.length;$("#notificationBadge").textContent=notifications.length}
function renderHome(){
 const d=daysTogether();$("#homeDebtPercent").textContent=debtPct().toFixed(1)+"%";$("#homeSavings").textContent=money(state.finance.fund);$("#homeNetWorth").textContent=money(netWorth());$("#daysTogether").textContent=d===null?"Set date":d.toLocaleString();
 $("#stepsCloser").textContent=`You've cleared ${money(paidTotal())} on the road towards the life you're building together.`;
 const milestones=["Now","Esperance","Zip-free","Debt-free","Home","Freedom"];$("#previewMilestones").innerHTML=milestones.map((m,i)=>`<span>${i<=Math.floor(debtPct()/20)?'●':'○'}<br>${m}</span>`).join("");$("#previewCar").style.setProperty("--progress",Math.min(82,5+debtPct()*.77)+"%");
 const next=getNotifications()[0];$("#todayHeadline").textContent=next?next.title:"A beautiful day to move forward.";$("#todayDetails").textContent=next?next.detail:"No urgent reminders.";
 const quotes=["Discipline today, freedom tomorrow.","Small steps today create beautiful tomorrows.","Your dreams are the seeds. Your actions are the water.","Every step takes you closer home."];$("#dailyMotivation").textContent=quotes[new Date().getDate()%quotes.length]
}
function accountProgress(id){return id==='home'?Math.min(100,debtPct()):pct(ORIGINAL[id]-state.finance[id],ORIGINAL[id])}
function renderJourney(){
 const list=$("#journeyDestinations");list.innerHTML=placeMap.map((p,i)=>{const pr=accountProgress(p.id), bal=p.id==='home'?totalDebt():state.finance[p.id];return `<button class="destination-card tappable" data-place="${p.id}"><span class="place-art">${p.art}</span><span><strong>${i+1}. ${p.name}</strong><small>${p.id==='home'?(totalDebt()<=0?'Unlocked':'Final destination'):money(bal)+' distance to go'} · ${pr.toFixed(0)}%</small><span class="progress"><i style="width:${pr}%"></i></span></span></button>`}).join("");
 $("#journeyCar").style.top=(64-Math.min(46,debtPct()*.46))+"%";$("#journeyPercent").textContent=debtPct().toFixed(1)+"%";$("#journeyCleared").textContent=money(paidTotal());$("#journeyEstimate").textContent=estimateCompletion();
 const active=placeMap.find(p=>p.id!=="home"&&Number(state.finance[p.id])>0)||placeMap.at(-1);$("#nextStepText").textContent=active.id==='home'?"Celebrate reaching Home":"Take a step towards "+active.name;$("#nextStepDue").textContent=active.id==='home'?"You made it":"Tap to record your next contribution";
 const completed=placeMap.filter(p=>p.id==='home'?totalDebt()<=0:state.finance[p.id]<=0);$("#journeyHighlights").innerHTML=`<div>🏆 <strong>${completed.length} destinations</strong><br><small>Completed</small></div><div>⭐ <strong>${debtPct().toFixed(1)}% travelled</strong><br><small>Keep going!</small></div>`
}
function estimateCompletion(){const hist=state.finance.history||[];if(hist.length<2)return "Add updates";const first=hist[0],last=hist.at(-1);const firstTotal=Object.keys(ORIGINAL).reduce((s,k)=>s+Number(first[k]??state.finance[k]),0),lastTotal=Object.keys(ORIGINAL).reduce((s,k)=>s+Number(last[k]??state.finance[k]),0),days=Math.max(1,(new Date(last.date)-new Date(first.date))/86400000),rate=(firstTotal-lastTotal)/days;if(rate<=0)return "Building pace";const end=new Date(Date.now()+totalDebt()/rate*86400000);return end.toLocaleDateString('en-AU',{month:'short',year:'numeric'})}
function renderGarden(){
 const level=gardenLevel();$("#gardenNetWorth").textContent=money(netWorth());$("#gardenSavings").textContent=money(state.finance.fund);const history=state.finance.history||[], growth=history.length>1?Math.max(0,(history.at(-1).fund||0)-(history.at(-2).fund||0)):0;$("#gardenGrowth").textContent=(growth>=0?"+":"")+money(growth);$("#gardenLevel").textContent="Level "+level;$("#gardenWorld").className=`garden-world level-${level}`;
 $("#gardenZones").innerHTML=gardenZones.map(z=>`<button class="zone-card tappable ${level<z.level?'locked':''}" data-zone="${z.id}">${z.icon} ${z.name}<small>${level<z.level?'Locked · Level '+z.level:'Level '+Math.min(level,z.level+2)}</small></button>`).join("")
}
function renderDreams(){const ds=state.dreams;$("#dreamCount").textContent=ds.length;$("#dreamSaved").textContent=money(ds.reduce((s,d)=>s+Number(d.saved||0),0));$("#dreamMonthly").textContent=money(ds.reduce((s,d)=>s+Number(d.monthly||0),0));$("#dreamOnTrack").textContent=ds.filter(d=>pct(d.saved,d.target)>=25||!d.date).length;$("#dreamGrid").innerHTML=ds.map(d=>`<button class="dream-card tappable" data-dream="${d.id}"><span class="dream-visual">${d.icon}</span><span class="dream-card-body"><strong>${esc(d.name)}</strong><small>${money(d.saved)} of ${money(d.target)}</small><span class="progress"><i style="width:${pct(d.saved,d.target)}%"></i></span></span></button>`).join("")}
function renderAdventures(){const trips=state.trips,mems=state.memories;$("#tripCount").textContent=trips.filter(t=>t.status==='Completed').length;$("#placeCount").textContent=new Set(trips.map(t=>t.destination).filter(Boolean)).size;$("#tripSpent").textContent=money(trips.reduce((s,t)=>s+Number(t.spent||0),0));$("#tripMemories").textContent=mems.filter(m=>m.type==='Travel').length;
 $("#passportStamps").innerHTML=trips.filter(t=>t.status==='Completed').map(t=>`<div class="stamp"><span>${t.icon||'✈️'}</span><strong>${esc(t.destination)}</strong><small>${dateText(t.date)}</small></div>`).join("")||'<div class="stamp"><span>✈️</span><strong>Next stamp</strong><small>Your adventure awaits</small></div>';
 $("#tripGrid").innerHTML=trips.map(t=>`<button class="trip-card tappable" data-trip="${t.id}"><span class="trip-visual">${t.icon||'🌍'}</span><span class="trip-card-body"><strong>${esc(t.destination)}</strong><small>${t.status||'Planning'} · ${dateText(t.date)}</small><small>Saved ${money(t.saved)} · Spent ${money(t.spent)}</small></span></button>`).join("")||'<button class="add-card" data-action="addTrip"><span>＋</span><div><strong>Plan your first adventure</strong><small>Create a trip, budget and itinerary.</small></div></button>';
 const next=trips.find(t=>t.status!=='Completed');const pr=next?pct(next.saved,next.budget):0;$("#tripProgress").style.width=pr+"%";$("#tripProgressLabel").textContent=next?`${money(next.saved)} of ${money(next.budget)} · ${pr.toFixed(0)}%`:"No next-trip goal yet"
}
function renderMemories(){const years=[...new Set(state.memories.map(m=>new Date(m.date).getFullYear()))].sort((a,b)=>b-a);$("#memoryFilters").innerHTML='<button class="'+(currentMemoryYear==='all'?'active':'')+'" data-year="all">All</button>'+years.map(y=>`<button class="${String(y)===String(currentMemoryYear)?'active':''}" data-year="${y}">${y}</button>`).join("");let mems=state.memories.slice().sort((a,b)=>new Date(b.date)-new Date(a.date));if(currentMemoryYear!=='all')mems=mems.filter(m=>new Date(m.date).getFullYear()==currentMemoryYear);$("#memoryTimeline").innerHTML=mems.map(m=>`<article class="memory-item tappable" data-memory="${m.id}"><header><div><strong>${esc(m.title)}</strong><small>${dateText(m.date)} · ${m.type||'Life'}</small></div><span>${m.icon||'❤️'}</span></header><p>${esc(m.note||'')}</p>${m.photoId?`<img class="memory-thumb" data-photo-id="${m.photoId}" alt="">`:m.photo?`<img class="memory-thumb" src="${m.photo}" alt="">`:''}</article>`).join("")||'<button class="add-card" data-action="addMemory"><span>＋</span><div><strong>Add your first memory</strong><small>Photos, milestones, adventures and notes.</small></div></button>';
 const d=daysTogether();$("#memoryCount").textContent=state.memories.length;$("#photoCount").textContent=state.memories.filter(m=>m.photoId||m.photo).length;$("#memoryPlaces").textContent=new Set(state.memories.map(m=>m.place).filter(Boolean)).size;$("#yearsTogether").textContent=d===null?'Set date':(d/365.25).toFixed(1);$("#journalCount").textContent=state.memories.filter(m=>m.note).length;hydratePhotos($("#memoryTimeline"))}
function automaticWins(){const wins=[];const add=(id,on,icon,title,detail,cat)=>{if(on)wins.push({id:'auto-'+id,icon,title,detail,category:cat,auto:true,date:new Date().toISOString().slice(0,10)})};add('first1000',state.finance.fund>=1000,'🐷','First $1,000 saved','A strong beginning.','Financial');add('zipmoney',state.finance.zipMoney<=0,'🌲','Forest Bend completed','One destination behind you.','Financial');add('zipfree',state.finance.zipMoney<=0&&state.finance.zipPlus<=0,'🌉','River Crossing completed','Your road is opening up.','Financial');add('car',state.finance.car<=0,'🚙','Scenic Lookout completed','Vehicle finance cleared.','Financial');add('debtfree',totalDebt()<=0,'🏡','Arrived Home','All tracked commitments cleared.','Financial');add('trip',state.trips.some(t=>t.status==='Completed'),'🌴','Adventure completed','Another beautiful memory.','Travel');add('dream',state.dreams.some(d=>pct(d.saved,d.target)>=100),'⭐','A dream came true','You made it happen.','Life');return wins}
function renderWins(){const all=[...automaticWins(),...state.wins];let wins=all;if(currentWinCategory!=='all')wins=wins.filter(w=>w.category===currentWinCategory);$("#winGrid").innerHTML=wins.map(w=>`<button class="win-card tappable" data-win="${w.id}"><span class="win-icon">${w.icon||'🏆'}</span><strong>${esc(w.title)}</strong><small>${esc(w.detail||'')}</small><small>${dateText(w.date)}</small></button>`).join("")||'<button class="add-card" data-action="addWin"><span>＋</span><div><strong>Add your first win</strong><small>Celebrate something meaningful today.</small></div></button>';
 $("#winCount").textContent=all.length;$("#milestoneCount").textContent=automaticWins().length;$("#goalsAchieved").textContent=state.dreams.filter(d=>pct(d.saved,d.target)>=100).length+state.trips.filter(t=>t.status==='Completed').length;const streak=calculateStreak();$("#streakDays").textContent=streak;$("#streakCount").textContent=streak>0?1:0;$("#streakGrid").innerHTML=`<div>🔥 <strong>Progress streak</strong><p>${streak} days</p><span class="streak-dots">${'●'.repeat(Math.min(streak,10))}${'○'.repeat(Math.max(0,10-streak))}</span></div><div>💚 <strong>Dream streak</strong><p>${state.dreams.filter(d=>d.saved>0).length} active dreams</p></div><div>📸 <strong>Memory streak</strong><p>${state.memories.length} moments kept</p></div>`}
function calculateStreak(){const dates=new Set((state.finance.history||[]).map(h=>String(h.date).slice(0,10)).concat(state.memories.map(m=>String(m.date).slice(0,10))));let n=0,d=new Date();for(let i=0;i<365;i++){const k=d.toISOString().slice(0,10);if(dates.has(k))n++;else if(i>0)break;d.setDate(d.getDate()-1)}return n}
function getNotifications(){const today=new Date();today.setHours(0,0,0,0);const notes=state.reminders.filter(r=>!r.done).map(r=>{const due=new Date(r.date+'T00:00:00');const diff=Math.round((due-today)/86400000);return{id:r.id,title:r.title,detail:diff<0?`${Math.abs(diff)} day${Math.abs(diff)!==1?'s':''} overdue`:diff===0?'Due today':diff===1?'Due tomorrow':`Due in ${diff} days`,date:r.date,status:diff<0?'overdue':diff===0?'today':'future'}}).sort((a,b)=>a.date.localeCompare(b.date));const nextTrip=state.trips.find(t=>t.date&&t.status!=='Completed');if(nextTrip){const diff=Math.ceil((new Date(nextTrip.date+'T00:00:00')-today)/86400000);if(diff>=0&&diff<=30)notes.push({id:'trip-'+nextTrip.id,title:`${nextTrip.destination} is getting close`,detail:`${diff} days to go`,status:'future'})}return notes}
function renderNotifications(){const ns=getNotifications();$("#notificationList").innerHTML=ns.map(n=>`<article class="notification-item ${n.status}"><strong>${esc(n.title)}</strong><small>${esc(n.detail)}</small>${String(n.id).startsWith('trip-')?'':`<button class="text-button" data-reminder-done="${n.id}">Mark done</button>`}</article>`).join("")||'<article class="notification-item"><strong>All clear 🌞</strong><small>No reminders need your attention.</small></article>'}

function openDetail(type,id){let html='';if(type==='place'){const p=placeMap.find(x=>x.id===id);const balance=id==='home'?totalDebt():state.finance[id],pr=accountProgress(id);html=`<div class="detail-hero">${p.art}</div><h2>${p.name}</h2><p>${p.description}</p><div class="detail-grid"><div class="detail-box"><small>Behind this milestone</small><strong>${id==='home'?'Financial freedom':accountLabels[id]}</strong></div><div class="detail-box"><small>Distance to go</small><strong>${money(balance)}</strong></div><div class="detail-box"><small>Progress</small><strong>${pr.toFixed(1)}%</strong></div><div class="detail-box"><small>Total cleared</small><strong>${money(id==='home'?paidTotal():ORIGINAL[id]-state.finance[id])}</strong></div></div>${id!=='home'?`<button class="button green detail-action" data-pay-account="${id}">Make a payment</button>`:''}`}
 else if(type==='zone'){const z=gardenZones.find(x=>x.id===id),level=gardenLevel(),locked=level<z.level;html=`<div class="detail-hero">${z.icon}</div><h2>${z.name}</h2><p>${z.description}</p><div class="detail-grid">${zoneStats(id)}</div>${locked?`<p>🔒 Reach Garden Level ${z.level} to fully unlock this zone.</p>`:''}`}
 else if(type==='dream'){const d=state.dreams.find(x=>x.id===id);html=`<div class="detail-hero">${d.icon}</div><h2>${esc(d.name)}</h2><p>${esc(d.notes||'')}</p><div class="detail-grid"><div class="detail-box"><small>Progress</small><strong>${pct(d.saved,d.target).toFixed(0)}%</strong></div><div class="detail-box"><small>Saved</small><strong>${money(d.saved)}</strong></div><div class="detail-box"><small>Target</small><strong>${money(d.target)}</strong></div><div class="detail-box"><small>Target date</small><strong>${dateText(d.date)}</strong></div></div><button class="button green detail-action" data-contribute-dream="${d.id}">Add money</button> <button class="button secondary detail-action" data-edit-dream="${d.id}">Edit plan</button>`}
 else if(type==='trip'){const t=state.trips.find(x=>x.id===id);html=`<div class="detail-hero">${t.icon||'🌍'}</div><h2>${esc(t.destination)}</h2><p>${esc(t.notes||'Your adventure diary.')}</p><div class="detail-grid"><div class="detail-box"><small>Status</small><strong>${t.status}</strong></div><div class="detail-box"><small>Date</small><strong>${dateText(t.date)}</strong></div><div class="detail-box"><small>Saved</small><strong>${money(t.saved)}</strong></div><div class="detail-box"><small>Budget / spent</small><strong>${money(t.budget)} / ${money(t.spent)}</strong></div></div><button class="button green detail-action" data-edit-trip="${t.id}">Edit trip</button> <button class="button secondary detail-action" data-trip-memory="${t.id}">Add memory</button>`}
 else if(type==='memory'){const m=state.memories.find(x=>x.id===id);html=`${m.photoId?`<img class="memory-thumb" data-photo-id="${m.photoId}" alt="">`:m.photo?`<img class="memory-thumb" src="${m.photo}" alt="">`:`<div class="detail-hero">${m.icon||'❤️'}</div>`}<h2>${esc(m.title)}</h2><p>${dateText(m.date)} · ${esc(m.place||m.type||'Life')}</p><p>${esc(m.note||'')}</p>`}
 else if(type==='win'){const w=[...automaticWins(),...state.wins].find(x=>x.id===id);html=`<div class="detail-hero">${w.icon||'🏆'}</div><h2>${esc(w.title)}</h2><p>${esc(w.detail||'')}</p><div class="detail-box"><small>Category</small><strong>${w.category}</strong></div>`}
 else html=genericDetail(type);
 $("#detailContent").innerHTML=html;$("#detailDialog").showModal();hydratePhotos($("#detailContent"))
}
function zoneStats(id){const dreamTotal=state.dreams.reduce((s,d)=>s+Number(d.saved||0),0);const map={savings:[["Current savings",money(state.finance.fund)],["Garden level","Level "+gardenLevel()]],safety:[["Emergency fund",money(state.finance.fund)],["Months protected",(state.finance.fund/3000).toFixed(1)]],prosperity:[["Net worth",money(netWorth())],["Journey cleared",debtPct().toFixed(1)+"%"]],dreams:[["Dreams planted",state.dreams.length],["Saved across dreams",money(dreamTotal)]],orchard:[["Long-term assets",money(dreamTotal)],["Dreams growing",state.dreams.filter(d=>d.saved>0).length]],homePath:[["Dream-home progress",money((state.dreams.find(d=>/home/i.test(d.name))||{}).saved||0)],["Next milestone","Keep building"]],freedom:[["Total cleared",money(paidTotal())],["Distance to freedom",money(totalDebt())]]};return (map[id]||[]).map(x=>`<div class="detail-box"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}
function genericDetail(type){const data={debtCleared:['📈','Journey cleared',`${debtPct().toFixed(1)}% of the original tracked commitments have been cleared.`],savings:['🐷','Savings',`Your current Freedom Fund is ${money(state.finance.fund)}.`],netWorth:['🪴','Net worth',`Assets and savings minus tracked commitments: ${money(netWorth())}.`],daysTogether:['❤️','Days together',state.profile.togetherSince?`${daysTogether().toLocaleString()} days since ${dateText(state.profile.togetherSince)}.`:'Set your together-since date to activate this counter.'],today:['🌞','Today',getNotifications()[0]?.detail||'No urgent reminders today.'],nextStep:['🗓️','Today’s next step','Choose one small action that moves you forward.'],nextTrip:['🗺️','Next adventure','Set a destination, budget and target date, then watch the progress grow.'],growth:['🌿','Growth this month','Compares your two latest saved progress updates.'],gardenLevel:['🌸','Garden level',`Your garden is currently Level ${gardenLevel()}. It grows as savings rise and commitments fall.`]};const x=data[type]||['🏡','Homebound','One step at a time. One dream at a time.'];return `<div class="detail-hero">${x[0]}</div><h2>${x[1]}</h2><p>${x[2]}</p>`}

function openForm(kind,id,extra={}){pendingForm={kind,id,extra};let title='',fields='';const input=(name,label,type='text',value='',full=false,opts='')=>`<label class="field ${full?'full':''}"><span>${label}</span>${type==='textarea'?`<textarea name="${name}">${esc(value)}</textarea>`:type==='select'?`<select name="${name}">${opts}</select>`:`<input name="${name}" type="${type}" value="${esc(value)}" ${type==='number'?'min="0" step="0.01"':''}></label>`}`;
 if(kind==='payment'){title='Record a step forward';fields=input('account','Destination','select',id,false,placeMap.filter(p=>p.id!=='home').map(p=>`<option value="${p.id}" ${p.id===id?'selected':''}>${p.name} (${accountLabels[p.id]})</option>`).join(''))+input('amount','Amount','number','')+input('date','Date','date',new Date().toISOString().slice(0,10));}
 if(kind==='reminder'){title='Add reminder';fields=input('title','Reminder','','')+input('date','Due date','date',new Date().toISOString().slice(0,10))+input('category','Category','select','',false,['Financial','Life','Travel','Dream'].map(x=>`<option>${x}</option>`).join(''));}
 if(kind==='dream'){const d=id?state.dreams.find(x=>x.id===id):{};title=id?'Edit dream':'Add a dream';fields=input('name','Dream name','text',d.name||'')+input('icon','Emoji','text',d.icon||'⭐')+input('target','Target amount','number',d.target||'')+input('saved','Saved so far','number',d.saved||0)+input('monthly','Monthly saving','number',d.monthly||0)+input('date','Target date','date',d.date||'')+input('notes','Notes','textarea',d.notes||'',true);}
 if(kind==='dreamMoney'){const d=state.dreams.find(x=>x.id===id);title='Add money to '+d.name;fields=input('amount','Contribution','number','')+input('note','Note','text','');}
 if(kind==='trip'){const t=id?state.trips.find(x=>x.id===id):{};title=id?'Edit adventure':'Plan a new adventure';fields=input('destination','Destination','text',t.destination||'')+input('icon','Emoji','text',t.icon||'✈️')+input('date','Travel date','date',t.date||'')+input('status','Status','select','',false,['Planning','Booked','Completed'].map(x=>`<option ${x===t.status?'selected':''}>${x}</option>`).join(''))+input('budget','Budget','number',t.budget||0)+input('saved','Saved','number',t.saved||0)+input('spent','Spent','number',t.spent||0)+input('notes','Notes / itinerary','textarea',t.notes||'',true);}
 if(kind==='memory'){title='Add a memory';fields=input('title','Title','text',extra.title||'')+input('date','Date','date',new Date().toISOString().slice(0,10))+input('type','Type','select','',false,['Life','Travel','Financial','Relationship','Dream'].map(x=>`<option ${x===extra.type?'selected':''}>${x}</option>`).join(''))+input('place','Place','text',extra.place||'')+input('icon','Emoji','text',extra.icon||'❤️')+input('note','Your memory','textarea','',true)+`<label class="field full"><span>Photo (optional)</span><input name="photo" type="file" accept="image/*"></label>`;}
 if(kind==='win'){title='Add a win';fields=input('title','What did you achieve?','text','')+input('date','Date','date',new Date().toISOString().slice(0,10))+input('category','Category','select','',false,['Financial','Life','Travel','Relationship','Personal'].map(x=>`<option>${x}</option>`).join(''))+input('icon','Emoji','text','🏆')+input('detail','Why it matters','textarea','',true);}
 if(kind==='profile'){title='Together settings';fields=input('togetherSince','Together since','date',state.profile.togetherSince||'')+input('names','Family name / label','text',state.profile.names||'');}
 if(kind==='backup'){title='Data & backup';fields=`<div class="detail-grid"><div class="detail-box"><small>Saved records</small><strong>${recordCount()}</strong></div><div class="detail-box"><small>Last backup</small><strong>${localStorage.getItem(BACKUP_TIME_KEY)?dateText(localStorage.getItem(BACKUP_TIME_KEY).slice(0,10)):'Not yet'}</strong></div></div><p>Your data stays on this phone. Export a portable JSON backup regularly.</p><button type="button" class="button green" id="exportBackup">Export backup</button> <label class="button secondary" style="display:inline-block">Import backup<input id="importBackup" type="file" accept="application/json" hidden></label>`;$("#formSave").hidden=true;}
 $("#formContent").innerHTML=`<h2>${title}</h2><div class="form-grid">${fields}</div>`;$("#formSave").hidden=kind==='backup';$("#formDialog").showModal();if(kind==='backup')setTimeout(bindBackupControls,0)
}
function recordCount(){return state.dreams.length+state.trips.length+state.memories.length+state.wins.length+state.reminders.length+(state.finance.history||[]).length}
async function submitForm(e){e.preventDefault();if(!pendingForm)return;const fd=new FormData(e.currentTarget),o=Object.fromEntries(fd.entries()),{kind,id}=pendingForm;let celebrateNow=false;
 if(kind==='payment'){const k=o.account,amount=Math.max(0,Number(o.amount));if(!amount)return toast('Enter an amount');const before=Number(state.finance[k]||0);state.finance[k]=Math.max(0,before-amount);state.finance.history.push({...clone(state.finance),date:o.date,note:`${placeMap.find(p=>p.id===k).name}: ${money(amount)}`});if(before>0&&state.finance[k]===0){state.wins.push({id:uid(),icon:placeMap.find(p=>p.id===k).icon,title:`${placeMap.find(p=>p.id===k).name} completed`,detail:`${accountLabels[k]} reached zero.`,category:'Financial',date:o.date});celebrateNow=true}}
 if(kind==='reminder')state.reminders.push({id:uid(),title:o.title,date:o.date,category:o.category,done:false});
 if(kind==='dream'){const d={id:id||uid(),name:o.name,icon:o.icon||'⭐',target:Number(o.target),saved:Number(o.saved),monthly:Number(o.monthly),date:o.date,notes:o.notes};if(id)Object.assign(state.dreams.find(x=>x.id===id),d);else state.dreams.push(d)}
 if(kind==='dreamMoney'){const d=state.dreams.find(x=>x.id===id),before=pct(d.saved,d.target);d.saved+=Number(o.amount||0);if(before<100&&pct(d.saved,d.target)>=100){state.wins.push({id:uid(),icon:'⭐',title:`${d.name} achieved`,detail:'A dream came true.',category:'Life',date:new Date().toISOString().slice(0,10)});celebrateNow=true}}
 if(kind==='trip'){const t={id:id||uid(),destination:o.destination,icon:o.icon||'✈️',date:o.date,status:o.status,budget:Number(o.budget),saved:Number(o.saved),spent:Number(o.spent),notes:o.notes};if(id)Object.assign(state.trips.find(x=>x.id===id),t);else state.trips.push(t)}
 if(kind==='memory'){const file=fd.get('photo');let photoId='';if(file&&file.size){photoId='photo-'+uid();await mediaPut(photoId,await compressImage(file))}state.memories.push({id:uid(),title:o.title,date:o.date,type:o.type,place:o.place,icon:o.icon,note:o.note,photoId})}
 if(kind==='win')state.wins.push({id:uid(),title:o.title,date:o.date,category:o.category,icon:o.icon,detail:o.detail});
 if(kind==='profile'){state.profile.togetherSince=o.togetherSince;state.profile.names=o.names}
 save();$("#formDialog").close();toast('Saved to this phone');if(celebrateNow)celebrate()
}
function compressImage(file){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1200,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=url})}
function bindBackupControls(){$("#exportBackup")?.addEventListener('click',exportBackup);$("#importBackup")?.addEventListener('change',e=>importBackup(e.target.files[0]))}
async function exportBackup(){try{const payload={app:'Homebound',version:window.HOMEBOUND_VERSION,exportedAt:new Date().toISOString(),state,media:await mediaAll()};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`Homebound_Backup_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);localStorage.setItem(BACKUP_TIME_KEY,payload.exportedAt);toast('Backup exported')}catch{toast('Backup could not be created')}}
function importBackup(file){if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const p=JSON.parse(reader.result);if(p.app!=='Homebound'||!p.state)throw Error();localStorage.setItem(SNAPSHOT_KEY,JSON.stringify(state));state=deepMerge(defaults,p.state);await mediaReplace(p.media||[]);saveRaw(state,false);renderAll();$("#formDialog").close();toast('Backup restored');}catch{toast('That is not a valid Homebound backup')}};reader.readAsText(file)}
function esc(v){return String(v??'').replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':'&quot;'}[c]))}

function clickHandler(e){const tab=e.target.closest('[data-tab-target]');if(tab)return setTab(tab.dataset.tabTarget);const act=e.target.closest('[data-action]');if(act){const a=act.dataset.action;if(a==='quickPayment')openForm('payment');if(a==='addReminder')openForm('reminder');if(a==='addDream')openForm('dream');if(a==='addTrip')openForm('trip');if(a==='addMemory')openForm('memory');if(a==='addWin')openForm('win');if(a==='backup')openForm('backup');if(a==='profile')openForm('profile');return}
 const detail=e.target.closest('[data-detail]');if(detail)return openDetail(detail.dataset.detail);const place=e.target.closest('[data-place]');if(place)return openDetail('place',place.dataset.place);const zone=e.target.closest('[data-zone]');if(zone)return openDetail('zone',zone.dataset.zone);const dream=e.target.closest('[data-dream]');if(dream)return openDetail('dream',dream.dataset.dream);const trip=e.target.closest('[data-trip]');if(trip)return openDetail('trip',trip.dataset.trip);const mem=e.target.closest('[data-memory]');if(mem)return openDetail('memory',mem.dataset.memory);const win=e.target.closest('[data-win]');if(win)return openDetail('win',win.dataset.win);
 const pay=e.target.closest('[data-pay-account]');if(pay){$("#detailDialog").close();return openForm('payment',pay.dataset.payAccount)}const contrib=e.target.closest('[data-contribute-dream]');if(contrib){$("#detailDialog").close();return openForm('dreamMoney',contrib.dataset.contributeDream)}const ed=e.target.closest('[data-edit-dream]');if(ed){$("#detailDialog").close();return openForm('dream',ed.dataset.editDream)}const et=e.target.closest('[data-edit-trip]');if(et){$("#detailDialog").close();return openForm('trip',et.dataset.editTrip)}const tm=e.target.closest('[data-trip-memory]');if(tm){const t=state.trips.find(x=>x.id===tm.dataset.tripMemory);$("#detailDialog").close();return openForm('memory',null,{title:t.destination+' Adventure',type:'Travel',place:t.destination,icon:t.icon})}
 const yd=e.target.closest('[data-year]');if(yd){currentMemoryYear=yd.dataset.year;return renderMemories()}const wc=e.target.closest('[data-category]');if(wc){currentWinCategory=wc.dataset.category;$$('#winFilters button').forEach(b=>b.classList.toggle('active',b===wc));return renderWins()}const rd=e.target.closest('[data-reminder-done]');if(rd){const r=state.reminders.find(x=>x.id===rd.dataset.reminderDone);if(r)r.done=true;save();return}
 const gt=e.target.closest('[data-garden-tap]');if(gt){const msg={butterfly:'The butterfly flutters through Dream Meadow 🦋',fish:'A fish jumps from the pond 🐠',bee:'A bee visits the greenhouse 🐝',bird:'A bird sings from the Orchard 🐦'}[gt.dataset.gardenTap];toast(msg)}
}
function bind(){document.addEventListener('click',clickHandler);$("#dynamicForm").addEventListener('submit',submitForm);$("#notificationButton").addEventListener('click',()=>{$("#notificationDrawer").classList.add('open');$("#notificationDrawer").setAttribute('aria-hidden','false')});$("#closeNotifications").addEventListener('click',()=>{$("#notificationDrawer").classList.remove('open');$("#notificationDrawer").setAttribute('aria-hidden','true')});$("#restoreRecovery").addEventListener('click',()=>{const s=safeParse(localStorage.getItem(SNAPSHOT_KEY),null);if(s){state=deepMerge(defaults,s);saveRaw(state,false);localStorage.removeItem(SNAPSHOT_KEY);renderAll();toast('Recovery copy restored')}});document.addEventListener('dblclick',e=>{if(e.target.closest('.topbar h1'))openForm('backup')});
 // Long press title opens backup visibly without adding an eighth tab.
 let timer;$('.topbar h1').addEventListener('touchstart',()=>timer=setTimeout(()=>openForm('backup'),700),{passive:true});$('.topbar h1').addEventListener('touchend',()=>clearTimeout(timer),{passive:true});
}
function init(){bind();renderAll();setTab(state.settings.lastTab||'home');setTimeout(()=>$("#splash").classList.add('hide'),950);if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
init();
})();
